name = "Full Scale"
author = "Nathan Wood"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3cd0b6395114c04dec121c5c6b8b8b4e55b3ad04504e9ced826be270488c7f59"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
datapack-folder = "config/paxi/datapacks"
